[project]
name = "bring-your-own-model"
version = "0.0.1"
description = "bring-your-own-model"
authors = [{ name = "John Doe", email = "john.doe@myemail.com" }]
dependencies = [
    "uipath",
    "uipath-langchain",
]
requires-python = ">=3.11"

[dependency-groups]
dev = [
    "uipath-dev",
]
