[project]
name = "file-attachments-chat-agent"
version = "0.0.1"
description = "file-attachments-chat-agent"
authors = [{ name = "John Doe", email = "john.doe@myemail.com" }]
dependencies = [
    "langchain-openai>=1.1.9",
    "uipath-langchain",
]
requires-python = ">=3.11"
