[project]
name = "agent"
version = "0.0.1"
description = "agent"
authors = [{ name = "John Doe", email = "john.doe@myemail.com" }]
dependencies = [
    "langchain-mcp-adapters>=0.2.1",
    "mcp>=1.24.0",
    "uipath-langchain>=0.1.0",
]
requires-python = ">=3.11"
