[project]
name = "simple-remote-mcp"
version = "0.0.1"
description = "simple-remote-mcp"
authors = [{ name = "John Doe", email = "john.doe@myemail.com" }]
dependencies = [
    "langchain>=1.1.0",
    "langchain-anthropic>=1.2.0",
    "langgraph>=1.0.4",
    "python-dotenv>=1.0.0",
    "anthropic>=0.57.1",
    "langchain-mcp-adapters>=0.1.14",
    "uipath",
    "uipath-langchain",
]
requires-python = ">=3.11"

[dependency-groups]
dev = [
    "uipath-dev",
]
