name: Publish Docs

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
      - chore/update-docs-token
    paths:
      - "docs/**"
      - "pyproject.toml"

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'UiPath/uipath-langchain-python' }}
    steps:
      - name: Trigger Publish Docs
        run: |
          repo_owner="uipath"
          repo_name="uipath-python"
          event_type="test-publish-docs"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {}}"
